name: Build omniORB Packages
on:
  workflow_dispatch:
    inputs:
      omniORB_version:
        description: 'omniORB version to build'
        required: true
        default: '4.3.3'
      runner_image:
        description: 'Linux Distro'
        required: true
        type: choice
        default: 'ubuntu-24.04'
        options:
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'
          - 'ubuntu-24.04'
      python_version:
        description: 'Python Version'
        required: true
        type: choice
        default: '3.13'
        options:
          - '2.7'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
      architecture:
        description: 'Architecture'
        required: true
        type: choice
        default: 'x64'
        options:
          - x64
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "omniORB Version: $OMNIORB_VERSION"
          echo "Linux Distro: $LINUX_DISTRO"
          echo "Python Version: $PYTHON_VERSION"
          echo "Architecture: $ARCHITECTURE"
        env:
          OMNIORB_VERSION: ${{ inputs.omniORB_version }}
          LINUX_DISTRO: ${{ inputs.runner_image }}
          PYTHON_VERSION: ${{ inputs.python_version }}
          ARCHITECTURE: ${{ inputs.architecture }}
